version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .type-dir.yaml
      - dir: feature
        ::
          - use: rule.feature_dir

  # feature_dir recurses into itself, allowing arbitrarily-named dirs under feature/ to contain
  # project.txt and/or a nested feature/ at any depth.
  - rule: feature_dir
    ::
      - dir:
          regex: '^[a-z0-9]+$'
        optional: true
        ::
          - file: project.txt
            optional: true
          - dir: feature
            optional: true
            ::
              - use: rule.feature_dir
