version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .dir-type.yaml
      - dir: assets
        ::
          # assets/ must contain at least 1 thumbnail_*.txt file (any_of).
          - any_of:
            ::
              - id: thumb32
                file: thumbnail_32x32.txt
              - id: thumb64
                file: thumbnail_64x64.txt
              - id: thumb128
                file: thumbnail_128x128.txt
