version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .type-dir.yaml
      - dir: feature
        id: feature_dir
        ::
          - use: rule.feature_dir
            id: feature
      - dir: tests
        ::
          - for:
              id: feature_item
              value: ${dir.feature_dir.dir.feature.dir.feature_name}
            ::
              - use: rule.test_feature
                with:
                  - id: feature
                    value: ${value.feature_item}

  - rule: feature_dir
    ::
      - dir:
          regex: '^(?<stem>[a-z0-9]+)$'
        id: feature_name
        optional: true
        ::
          - file: project.txt
            optional: true
            id: project
          - dir: feature
            optional: true
            id: subfeatures
            ::
              - use: rule.feature_dir

  - rule: test_feature
    with:
      - id: feature
        type: rule.feature_dir
    ::
      - dir: '${with.feature.regex.stem}-test'
        ::
          - for:
              id: project
              value: ${with.feature.file.project}
            ::
              - file: project.test.txt
          - for:
              id: sub_feature_dir
              value: ${with.feature.dir.subfeatures}
            ::
              - dir: feature
                ::
                  - for:
                      id: nested_feature
                      value: ${value.sub_feature_dir.dir.feature_name}
                    ::
                      - use: rule.test_feature
                        with:
                          - id: feature
                            value: ${value.nested_feature}
