version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .dir-type.yaml
      - dir: shards
        ::
          # shards/ must contain 2 to 4 files matching <N>.txt (N is 0-9) (min/max).
          - file:
              regex: '^[0-9]\.txt$'
            min: 2
            max: 4
