mod check_capture_requires_id;
mod check_duplicate_id;
mod check_entry_combination;
mod check_entry_refs;
mod check_fetch;
mod check_id_capture;
mod check_match_exhaustive;
mod check_pattern;
mod check_rule_var_scope;
mod check_undefined_rule;
pub(crate) mod check_with_compat;
mod check_with_keys;
mod check_with_shapes;
mod id_shape;
pub(crate) mod id_shape_derive;
mod pattern_util;
mod walk;
pub use check_capture_requires_id::check_capture_requires_id;
pub use check_duplicate_id::check_duplicate_id;
pub use check_entry_combination::check_entry_combination;
pub use check_entry_refs::check_entry_refs;
pub use check_fetch::check_fetch;
pub use check_id_capture::check_id_capture_required;
pub use check_match_exhaustive::check_match_exhaustive;
pub use check_pattern::check_pattern;
pub use check_rule_var_scope::check_rule_var_scope;
pub use check_undefined_rule::check_undefined_rule;
pub use check_with_compat::check_with_compat;
pub use check_with_keys::check_with_keys;
pub use check_with_shapes::check_with_shapes;
pub use pattern_util::named_captures;
