version: 0

entry: root

rules:
  - rule: root
    ::
      - file: .type-dir.yaml
      # regex file entry: accepts all matching files (0.txt / 1.txt / 2.txt).
      - file:
          regex: '^[0-9]\.txt$'
